#!/bin/bash

# general profile management environmental variables
# load the environment

# we must play with the IFS because eval is funny about splitting on
# newlines in the source
old_ifs="$IFS"
IFS="\n"
eval $(python3 -m bimhaw.env)
IFS="$old_ifs"

# startup file for non-login interactive shell
. "$ACTIVE_BASH_DIR/interactive.bash"


####

# code in here won't be run. This is just a cage for programs that
# inctrospect your dotfiles to see if the correct initialization is
# present, annoying I know but something we have to deal with...

if false; then

>&2 echo "sanity check; shouldn't be running this"

fi
