#!/bin/sh

. "$HOME/.bimhaw/env.sh"

# WARNING: if you delete .bash_profile, this file becomes part of
# bash's startup sequence, which means this file suddenly has to cater
# for two different shells.

. "$ACTIVE_SH_DIR/login.sh"



