#!/bin/sh

# load the environment
# we must play with the IFS because eval is funny about splitting on
# newlines in the source
# old_ifs="$IFS"
# IFS="
# "
# eval $(python3 -m bimhaw.env)
# IFS="$old_ifs"

. "$HOME/.bimhaw/env.sh" || exit 1
# WARNING: if you delete .bash_profile, this file becomes part of
# bash's startup sequence, which means this file suddenly has to cater
# for two different shells.

. "$BIMHAW_DIR/active/shells/sh/login.sh"



